ulo/accounts/urls.py
"""
Accounts URL Configuration
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	# Email verification
	url(r'^verification/(?P<token>[^<>\'"@]+)/$',
		views.EmailVerificationView.as_view(), name='verification'),
	url(r'^resend_verification/$',
		views.ResendEmailVerificationView.as_view(), name='resend_verification'),


	# Password reset
	url(r'^password_reset/$', 
		views.PasswordResetBeginView.as_view(), name='password_reset_begin'),
	url(r'^password_reset/email/$', 
		views.PasswordResetEmailView.as_view(), name='password_reset_email'),
	url(r'^password_reset/sent/$', 
		views.PasswordResetSentView.as_view(), name='password_reset_sent'),
	url(r'^password_reset/(?P<token>[^<>\'"@]+)/$', 
		views.PasswordResetView.as_view(), name='password_reset'),


	# Not my account
	url(r'^not_my_account/confirmed/$',
		views.NotMyAccountConfirmedView.as_view(), name='not_my_account_confirmed'),
	url(r'^not_my_account/$',
		views.NotMyAccountNoUserView.as_view(), name='not_my_account_no_user'),
	url(r'^not_my_account/(?P<token>[^<>\'"@]+)/$',
		views.NotMyAccountView.as_view(), name='not_my_account'),


	# Token expired
	url(r'^token_expired/$', views.TokenExpiredView.as_view(), name='token_expired'),
	

	# Account Deactivation.
	url(r'^deactivate/$', views.DeactivateAccountView.as_view(), name='deactivate'),
	url(r'^deactivated/$', views.DeactivatedAccountView.as_view(), name='deactivated')

]

# ----------------------------------------------------------------------------------------

ulo/config/urls.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports

# Core django imports
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

# Thrid party app imports

# Project imports
from pages.views import HomeAuthView, NavigationView
from users.views import SignUpView, LoginView, LogoutView

# ----------------------------------------------------------------------------------------


# TO SERVE MEDIA FILES IN DEVELOPMENT ONLY
from django.conf.urls.static import static

# ----------------------------------------------------------------------------------------

urlpatterns = [

	# PAGES APP

	url(r'^$', HomeAuthView.as_view(), name='home'),

	# Site navigation when js is disabled.
	url(r'^navigation/$', NavigationView.as_view(), name='navigation'),


	# SEARCH APP

	url(r'^search/', include('search.urls', namespace='search')),


	# POSTS APP

	url(r'^post/', include('posts.urls', namespace='posts')),


	# USERS APP

	url(r'^user/', include('users.urls', namespace='users')),

	url(r'^signup/$', SignUpView.as_view(), name='signup'),

	url(r'^login/(\?redirect_to=(?P<redirect_to>[^<>\'"@]*/))?$', LoginView.as_view(), name='login'),
	
	url(r'^logout/$', LogoutView.as_view(), name='logout'),


	# COMMENTS APP

	url(r'^comment/', include('comments.urls', namespace='comments')),


	# ACCOUNTS APP
	
	url(r'^accounts/', include('accounts.urls', namespace='accounts')),


	# SETTINGS APP

	url(r'^settings/', include('settings.urls', namespace='settings')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ----------------------------------------------------------------------------------------

ulo/posts/urls.py
"""
Posts URL Configuration
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	# Post form
	url(r'^$', views.PostView.as_view(), name='post'),

	# Post detail page
	url(r'^(?P<pk>[\d]+)/$', views.PostDetailView.as_view(), name='detail'),

	# Post vote
	url(r'^(?P<pk>[\d]+)/vote/$', views.PostVoteView.as_view(), name='vote'),

	# Image post handler
	url(r'^image/$', views.PostImageView.as_view(), name='image'),
	
	# Video post handler
	url(r'^video/$', views.PostVideoView.as_view(), name='video'),

	# Comment
	url(r'^(?P<pk>[\d]+)/comment/$', views.PostCommentView.as_view(), name='comment'),
	url(r'^(?P<pk>[\d]+)/comment/load/$', views.PostCommentLoadView.as_view(), name='comment_load'),

	# Update post
	url(r'^(?P<pk>[\d]+)/update/$', views.PostUpdateView.as_view(), name='update'),
	
	# Delete post
	url(r'^(?P<pk>[\d]+)/delete/$', views.PostDeleteView.as_view(), name='delete'),

	# Report post
	url(r'^(?P<pk>[\d]+)/report/$', views.PostReportView.as_view(), name='report'),
	url(r'^report/complete/$', views.PostReportCompleteView.as_view(), name='report_complete'),

	# Post actions menu (JS disabled)
	url(r'^(?P<pk>[\d]+)/actions/$', views.PostActionsView.as_view(), name='actions'),

]

# ----------------------------------------------------------------------------------------

ulo/settings/urls.py
"""
Settings URL Configuration
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	url(r'^account/$', views.AccountSettingsView.as_view(), name='account'),

	url(r'^password/$', views.PasswordSettingsView.as_view(), name='password'),

	# url(r'^notifications/$',
	# 	views.NotificationSettingsView.as_view(), name='notifications'),
]

# ----------------------------------------------------------------------------------------

ulo/accounts/models.py
from django.db import models

# Create your models here.

ulo/accounts/views.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals
import re

# Core django imports
from django.contrib import messages
from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.http import Http404, JsonResponse
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.utils.functional import cached_property
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.cache import never_cache

# Thrid party app imports

#Project imports
from .forms import *
from .viewmixins import *
from emails.emails import verify_email, reset_password_email
from users.utils import NOT_MY_ACCOUNT
from ulo.sessions import LinkViewsSession
from ulo.tokens import(
	InvalidToken, NotMyAccountTokenGenerator, ResetPasswordTokenGenerator, 
	VerifyEmailTokenGenerator
)
from ulo.utils import get_referer_path, get_messages_json
from ulo.views import UloView, UloFormView, UloUpdateView
from ulo.viewmixins import UloLogoutRequiredMixin

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

def redirect_to_expired():

	return redirect(reverse('accounts:token_expired'))

# ----------------------------------------------------------------------------------------

def censor_email(email):

	return re.sub(
	
		r'^([^@]{1,2})[^@]*(@[^.]{1,2}).*(\.[^.]*)$', r'\1******\2******\3', email
	
	)

# ----------------------------------------------------------------------------------------

class TokenExpiredView(UloView):

	template_name = 'accounts/token_expired.html'
	

	def get(self, request, *args, **kwargs):

		return render(request, self.template_name, {})

# ----------------------------------------------------------------------------------------

class DeactivateAccountView(LoginRequiredMixin, UloFormView):

	redirect_field_name = 'redirect_to'
	template_name = 'accounts/deactivate.html'
	form_class = DeactivateAccountForm


	def get_form_kwargs(self):
		
		kwargs = super(DeactivateAccountView, self).get_form_kwargs()
		
		kwargs.update({'instance': self.request.user })
		
		return kwargs


	def form_valid(self, form):

		self.request.user.deactivate_account()
		
		logout(self.request)
		
		LinkViewsSession(self.request).set('deactivate_account', True)
		
		return redirect(reverse('accounts:deactivated'))

# ----------------------------------------------------------------------------------------

class DeactivatedAccountView(UloLogoutRequiredMixin, UloView):
	"""
	Display page informing the user that their account has been deactivated.
	"""

	template_name = 'accounts/deactivated.html'


	def get(self, request, *args, **kwargs):
		
		if LinkViewsSession(request).get('deactivate_account'):
		
			return super(DeactivatedAccountView, self).get(request, *args, **kwargs)
		
		raise Http404()

# ----------------------------------------------------------------------------------------

class NotMyAccountView(TokenValidationMixin, UloUpdateView):
	"""
	Render the form that suspends the account/email address.
	"""

	form_class = NotMyAccountForm
	template_name = 'accounts/not_my_account.html'


	def get_success_url(self):
		
		return reverse('accounts:not_my_account_confirmed')


	def get(self, request, *args, **kwargs):

		try:

			user = self.get_object()

			# The logged in user is claiming that this is not their account.
			if request.user.id == user.id:
				
				messages.error(
				
					request,
					_('You can deactivate your account from the settings page.')
				
				)

				return redirect(get_referer_path(request, error_path=reverse('home')))


			# Account already verified.
			if user.email_confirmed:

				raise PermissionDenied()


			# Account already suspended.
			if user.block == NOT_MY_ACCOUNT:

				raise PermissionDenied()

			
		# The email address is no longer associated with an account.
		except get_user_model().DoesNotExist:

			LinkViewsSession(request).set('not_my_account_no_user', True)

			return redirect(reverse('accounts:not_my_account_no_user'))


		except (InvalidToken, PermissionDenied):

			return redirect_to_expired()


		return super(NotMyAccountView, self).get(request, *args, **kwargs)


	def get_context_data(self, **kwargs):
		"""
		"""		

		context = super(NotMyAccountView, self).get_context_data(**kwargs)

		user = self.get_object()

		context.update({

			'username': user.username, 
			'email': censor_email(user.email)

		})
		
		return context


	@cached_property
	def validate_token(self):

		return NotMyAccountTokenGenerator().check_token(

			token=self.kwargs.get('token'), salt='not_my_account', 
			fail_silently=False, max_age=172800 # 2 days

		)


	def form_valid(self, form):
		
		form.save()
		
		LinkViewsSession(self.request).set('not_my_account', True)
		
		return super(NotMyAccountView, self).form_valid(form)


# ----------------------------------------------------------------------------------------

class NotMyAccountConfirmedView(UloView):
	"""
	Confirm that the account/email address have been suspended.
	"""

	template_name = 'accounts/not_my_account_confirmed.html'


	def get(self, request, *args, **kwargs):

		if LinkViewsSession(request).get('not_my_account'):
		
			return super(NotMyAccountConfirmedView, self).get(request, *args, **kwargs)
		
		raise Http404()

# ----------------------------------------------------------------------------------------

class NotMyAccountNoUserView(UloView):
	"""
	Rendered when the email address is no longer associated to an account.
	"""

	template_name = 'accounts/not_my_account_no_user.html'


	def get(self, request, *args, **kwargs):
		
		if LinkViewsSession(request).get('not_my_account_no_user'):
		
			return super(NotMyAccountNoUserView, self).get(request, *args, **kwargs)
		
		raise Http404()

# ----------------------------------------------------------------------------------------

@method_decorator(never_cache, name='get')
class EmailVerificationView(LoginRequiredMixin, UloView):
	"""
	Set user.email_confirmed=True if the token is valid.
	"""

	redirect_field_name = 'redirect_to'
	

	def get(self, request, token, *args, **kwargs):

		user = VerifyEmailTokenGenerator().check_token(
		
			token=token, salt='email_verification', max_age=604800 # 7 days
		
		)

		if user != None:

			if request.user != user:
				
				messages.info(request, 
					
					mark_safe(
						_(					
							
							'Please sign is as <b class="bold">@%(username)s</b> to \
								confirm your email address.'

						) % {'username':user.username}
					)
				)
			
			else:
			
				user.email_confirmed = True;

				user.save()
			
				messages.success(request, 
			
					_('Thank you for confirming your email address!')
			
				)


			return redirect(get_referer_path(request))

		
		return redirect_to_expired()

# ----------------------------------------------------------------------------------------

class ResendEmailVerificationView(LoginRequiredMixin, UloView):
	"""
	Send the user a confirmation email to confirm their email address.
	"""

	def get(self, request, *args, **kwargs):

		if verify_email(request.user):
			
			messages.success(request, 
			
				_('We have sent you a confirmation email.')
			
			)

			status = 200
		
		else:
		
			messages.error(request, 
		
				_('We failed to send you a confirmation email. Please try again later.')
		
			)

			status = 500


		if request.is_ajax():

			return JsonResponse({'messages': get_messages_json(request)}, status=status)

		return redirect( get_referer_path(request) )

# ----------------------------------------------------------------------------------------

class PasswordResetBeginView(PasswordResetMixin, UloLogoutRequiredMixin, UloFormView):
	"""
	"""

	template_name = 'accounts/password_reset_begin.html'
	form_class = PasswordResetBeginForm


	def get_success_url(self):

		return reverse('accounts:password_reset_email')


	def get(self, request, *args, **kwargs):

		self.delSession()

		return super(PasswordResetBeginView, self).get(request, *args, **kwargs)


	def form_valid(self, form):

		self.setSession(form.get_email())
		
		return super(PasswordResetBeginView, self).form_valid(form)

# ----------------------------------------------------------------------------------------

@method_decorator(never_cache, name='get')
class PasswordResetEmailView(PasswordResetMixin, UloLogoutRequiredMixin, UloView):
	"""

	"""

	template_name = 'accounts/password_reset_email.html'


	def get_success_url(self):

		return reverse('accounts:password_reset_sent')


	def get(self, request, *args, **kwargs):
		
		email = self.getSession()

		if email==None:
			return self.redirect_to_start()

		kwargs['email'] = censor_email(email)

		return super(PasswordResetEmailView, self).get(request, *args, **kwargs)


	def post(self, request, *args, **kwargs):

		email = self.getSession()

		try:

			UserModel = get_user_model()

			user = UserModel.objects.get(email=email)

			if reset_password_email(user=user) == 0:
				raise UserModel.DoesNotExist

		except UserModel.DoesNotExist:

			msg = _(

				'Your session expired. Please try again.' if email==None \
				else 'We failed to send your password reset link. Please try again.'

			)

			messages.error(request, msg)
			
			return self.redirect_to_start()

		return redirect( self.get_success_url() )

# ----------------------------------------------------------------------------------------

class PasswordResetSentView(PasswordResetMixin, UloLogoutRequiredMixin, UloView):
	"""
	End the password reset process and display a page informing the user that an email

ulo/templates/accounts/deactivate.html
{% extends base_template %}
{% load staticfiles %}

{% block css %}
	<link class="css_file" href="{% static 'css/accounts/deactivate.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}

{% block content %}
<div id="deactivate">

	<div class="centre">

		<h1>We are sad to see you go.</h1>

		<p class="text">
			Remember, you can reactivate your account by logging in before your information is deleted permanently in 30 days time.
		</p>

		<form id="deactivate_form" class="cf" action="{% url 'accounts:deactivate' %}" method="post">

			{% csrf_token %}

			{% if form.non_field_errors %}
			<div id="deactivate_form_errors" class="form_errors">
				
				{% for error in form.non_field_errors %}
				<p class="validation error">{{ error }}</p>
				{% endfor %}
			
			</div>
			{% endif %}

			
			<div id="deactivate_password_container">

				{% for error in form.password.errors %}
					<p class="validation error">{{ error }}</p>
				{% endfor %}

				{{ form.password }}

			</div>


			<input id="deactivate_submit" type="submit" name="submit" value="Deactivate">

			<a id="deactivate_cancel" href="{% url 'settings:account' %}" title="Cancel">
				Cancel
			</a>
			

		</form>

	</div>

</div>
{% endblock content %}

{% block js %}
	<script class="js_file" src="{% static 'js/helpers/validation.js' %}"></script>
	<script class="js_file" src="{% static 'js/accounts/deactivate.js' %}"></script>
{% endblock js %}

ulo/templates/accounts/deactivated.html
{% extends base_template %}
{% load staticfiles %}

{% block css %}
	<link class="css_file" href="{% static 'css/accounts/deactivated.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}

{% block content %}
<div id="deactivated">

	<div class="centre">

		<h1>Account Deactivated</h1>
		<p class="bold">Your account has been deactivated and will be deleted permanently in 30 days.</p>

		<p>To reactivate your account <a class="bold" href="{% url 'login' %}" title="Log in">log in</a> before we delete it permanently.</p>

		<p class="valediction">Good-bye for now.</p>

	</div>
	
</div>
{% endblock content %}

ulo/templates/accounts/not_my_account.html
{% extends base_template %}
{% load staticfiles %}

{% block css %}
	<link class="css_file" href="{% static 'css/accounts/not_my_account.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}

{% block content %}
<div id="not_my_account">

	<h1 class="panel highlight">Not your account?</h1>

	<p class="panel text">
		Please confirm that you did not sign up for the Ulo account <b>@{{username}}</b> with the email address <b>{{email}}</b>.
	</p>

	<p class="panel text">
		To prevent further misuse of your email address, the account (including your email address) will be suspended from Ulo for 30 days. The account will be removed permanently following the suspension and your email address will be made available for use on Ulo. Contact us should you wish to create an account with this email address during the 30 day suspension.
	</p>

	<form id="not_my_account_form" action="{% url 'accounts:not_my_account' form.token.value %}" method="post">
		
		{% csrf_token %}

		{% if form.non_field_errors %}
			<div id="not_my_account_form_errors" class="form_errors">
				{% for error in form.non_field_errors %}
				<p class="validation error">{{ error }}</p>
				{% endfor %}
			</div>
		{% endif %}
	
		<input id="not_my_account_submit" type="submit" name="submit" value="This is not my account">
		<a id="not_my_account_cancel" href="{% url 'home' %}" title="Cancel">Cancel</a>
	
	</form>

	

	<p class="text">
		If this account does belong to you but you would like to deactivate it, visit your <a class="bold highlight" href="{% url 'settings:account' %}" title="Settings">account settings.</a>
	</p>

</div>
{% endblock content %}

ulo/templates/accounts/not_my_account_confirmed.html
{% extends base_template %}
{% load staticfiles %}

{% block css %}
	<link class="css_file" href="{% static 'css/accounts/not_my_account_confirmed.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}

{% block content %}
<div id="not_my_account_confirmed">

	<div class="centre">

		<h1>The account has been suspended and will be removed permanently in 30 days.</h1>
		
		<h2>Why was my email address used?</h2>
		
		<p>When creating an Ulo account another user may have entered your email address by mistake or was attempting to engage in misconduct. Your report will help identify improper behaviour on Ulo.</p>
	
	</div>
	
</div>
{% endblock content %}

ulo/templates/accounts/not_my_account_no_user.html
{% extends base_template %}
{% load staticfiles %}

{% block css %}
  <link class="css_file" href="{% static 'css/accounts/not_my_account_no_user.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}

{% block content %}
<div id="not_my_account_no_user">

	<h1 class="panel">Your email address is not associated with an Ulo account.</h1>

	<p class="panel">
		We did not find an account registered to your email address. To create an account <a class="bold" href="{% url 'signup' %}" title="Sign up">sign up</a>.
	</p>

	<h2 class="panel">Why did I receieve an email from Ulo?</h2>
	
	<ul class="list">
		<li>Another user entered your email address by mistake when creating an account.</li>
		<li>Your email address was previously associated with an Ulo account.</li>
	</ul>

</div>
{% endblock content %}

ulo/templates/accounts/password_reset.html
{% extends base_template %}
{% load staticfiles %}

{% block css %}
	<link class="css_file" href="{% static 'css/accounts/password_reset.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}

{% block content %}
<div id="password_reset">

	<div class="centre">

		<h1 class="panel thin">Reset your password</h1>
		
		<p class="panel">Your password must be at least 6 characters long and combine letters, numbers or punctuation.</p>

		<div class="user_summary panel cf">
		
			<img src="{{ form.instance.thumbnail.url }}">

			<div class="names">
				<span class="ellipsis"><b>{{ form.instance.name }}</b></span>
				<span class="ellipsis">@{{ form.instance.username }}</span>
			</div>
		
		</div>

		<form id="password_reset_form" action="{% url 'accounts:password_reset' form.token.value %}" method="post">

			{% csrf_token %}

			<div class="field panel">

				{{ form.password.label_tag }}

				<div id="password_container">
	
					{% for error in form.password.errors %}
					<p class="validation error">{{ error }}</p>
					{% endfor %}

					{{ form.password }}

				</div>

			</div>

			<div class="field panel">

				{{ form.verify_password.label_tag }}
				
				<div id="verify_password_container">

					{% for error in form.verify_password.errors %}
					<p class="validation error">{{ error }}</p>
					{% endfor %}

					{{ form.verify_password }}

				</div>

			</div>

			<input id="password_reset_submit" class="panel" name="submit" type="submit" value="Save">

		</form>

	</div>
</div>
{% endblock content %}

{% block js %}
	<script class="js_file" src="{% static 'js/helpers/validation.js' %}"></script>
	<script class="js_file" src="{% static 'js/accounts/password_reset.js' %}"></script>
{% endblock js %}

ulo/templates/accounts/password_reset_begin.html
{% extends base_template %}
{% load staticfiles %}

{% block css %}
	<link class="css_file" href="{% static 'css/accounts/password_reset_begin.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}

{% block content %}
<div id="password_reset_begin">

	<div class="wrapper">

		<h1 class="panel thin">Find your account</h1>

		<form id="password_reset_begin_form" class="panel" action="{% url 'accounts:password_reset_begin' %}" method="post">

			{% csrf_token %}

			{% if form.non_field_errors %}
			<div id="password_reset_begin_form_errors" class="form_errors">
				{% for error in form.non_field_errors %}
				<p class="validation error">{{ error }}</p>
				{% endfor %}
			</div>
			{% endif %}
				
			<div id="email_container">

				{% for error in form.email.errors %}
					<p class="validation error">{{ error }}</p>
				{% endfor %}

				{{ form.email }}

			</div>

			<input id="password_reset_begin_submit" class="panel" name="submit" type="submit" value="Search">
		
		</form>

	</div>

</div>
{% endblock content %}

ulo/templates/accounts/password_reset_email.html
{% extends base_template %}
{% load staticfiles i18n %}

{% block css %}
	<link class="css_file" href="{% static 'css/accounts/password_reset_email.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}

{% block content %}
<div id="password_reset_email">

	<div class="centre">

		<h1 class="panel thin">Send my password reset link</h1>

		<p class="panel">We will send your password reset link to the email address <b>{{ email }}</b></p>

		<form id="password_reset_email_form" class="panel" action="{% url 'accounts:password_reset_email' %}" method="post">
			
			{% csrf_token %}

			<input class="box_border" name="submit" type="submit" value="Send">
			
			<a class="box_border" href="{% url 'accounts:password_reset_begin' %}">Cancel</a>

		</form>

	</div>

</div>
{% endblock content %}

ulo/templates/accounts/password_reset_sent.html
{% extends base_template %}
{% load staticfiles %}

{% block css %}
	<link class="css_file" href="{% static 'css/accounts/password_reset_sent.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}

{% block content %}
<div id="password_reset_sent">

	<div class="centre">

		<h1 class="panel thin">We have sent you an email</h1>

		<p class="panel">Follow the link in the email to reset your password. Don't forget to check your email folders such as <b>junk</b>, <b>spam</b> or <b>social</b> if you cannot see the email.</p>

	</div>

</div>
{% endblock content %}

ulo/templates/accounts/token_expired.html
{% extends base_template %}
{% load staticfiles %}

{% block css %}
	<link class="css_file" href="{% static 'css/accounts/token_expired.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}


{% block content %}
<div id="token_expired">

	<h1 class="thin">Sorry, this link has expired.</h1>

</div>
{% endblock content %}