ulo/config/urls.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports

# Core django imports
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

# Thrid party app imports

# Project imports
from pages.views import HomeAuthView, NavigationView
from users.views import SignUpView, LoginView, LogoutView

# ----------------------------------------------------------------------------------------


# TO SERVE MEDIA FILES IN DEVELOPMENT ONLY
from django.conf.urls.static import static

# ----------------------------------------------------------------------------------------

urlpatterns = [

	# PAGES APP

	url(r'^$', HomeAuthView.as_view(), name='home'),

	# Site navigation when js is disabled.
	url(r'^navigation/$', NavigationView.as_view(), name='navigation'),


	# SEARCH APP

	url(r'^search/', include('search.urls', namespace='search')),


	# POSTS APP

	url(r'^post/', include('posts.urls', namespace='posts')),


	# USERS APP

	url(r'^user/', include('users.urls', namespace='users')),

	url(r'^signup/$', SignUpView.as_view(), name='signup'),

	url(r'^login/(\?redirect_to=(?P<redirect_to>[^<>\'"@]*/))?$', LoginView.as_view(), name='login'),
	
	url(r'^logout/$', LogoutView.as_view(), name='logout'),


	# COMMENTS APP

	url(r'^comment/', include('comments.urls', namespace='comments')),


	# ACCOUNTS APP
	
	url(r'^accounts/', include('accounts.urls', namespace='accounts')),


	# SETTINGS APP

	url(r'^settings/', include('settings.urls', namespace='settings')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ----------------------------------------------------------------------------------------

ulo/posts/urls.py
"""
Posts URL Configuration
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	# Post form
	url(r'^$', views.PostView.as_view(), name='post'),

	# Post detail page
	url(r'^(?P<pk>[\d]+)/$', views.PostDetailView.as_view(), name='detail'),

	# Post vote
	url(r'^(?P<pk>[\d]+)/vote/$', views.PostVoteView.as_view(), name='vote'),

	# Image post handler
	url(r'^image/$', views.PostImageView.as_view(), name='image'),
	
	# Video post handler
	url(r'^video/$', views.PostVideoView.as_view(), name='video'),

	# Comment
	url(r'^(?P<pk>[\d]+)/comment/$', views.PostCommentView.as_view(), name='comment'),
	url(r'^(?P<pk>[\d]+)/comment/load/$', views.PostCommentLoadView.as_view(), name='comment_load'),

	# Update post
	url(r'^(?P<pk>[\d]+)/update/$', views.PostUpdateView.as_view(), name='update'),
	
	# Delete post
	url(r'^(?P<pk>[\d]+)/delete/$', views.PostDeleteView.as_view(), name='delete'),

	# Report post
	url(r'^(?P<pk>[\d]+)/report/$', views.PostReportView.as_view(), name='report'),
	url(r'^report/complete/$', views.PostReportCompleteView.as_view(), name='report_complete'),

	# Post actions menu (JS disabled)
	url(r'^(?P<pk>[\d]+)/actions/$', views.PostActionsView.as_view(), name='actions'),

]

# ----------------------------------------------------------------------------------------

ulo/posts/views.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.db import connection, IntegrityError, OperationalError, transaction
from django.db.models import F
from django.http import Http404, JsonResponse
from django.shortcuts import redirect
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _
from django.views.generic.edit import DeletionMixin

# Thrid party app imports

# Project imports
from .forms import PostForm, PostUpdateForm, PostOptionForm, PostReportForm
from .models import Post, PostOption, PostVote
from .search import post_search
from .utils import DISABLED, get_category
from comments.forms import CommentForm
from comments.models import Comment
from ulo.handlers import (
	MediaUploadHandler, MemoryMediaUploadHandler, TemporaryMediaUploadHandler
)
from ulo.sessions import LinkViewsSession
from ulo.utils import (
	dictfetchmany, get_messages_json, get_cid, get_referer_path, postfetchone, 
	validate_cid
)
from ulo.viewmixins import UloLoginRequiredMixin, UloOwnerRequiredMixin
from ulo.views import UloView, UloFormView, UloUpdateView, UloUploadView

# ----------------------------------------------------------------------------------------




# POST UPLOAD VIEWS
# ----------------------------------------------------------------------------------------

class PostAttrsMixin(object):
	"""
	Define the class attributes common to PostView and _PostUploadView.
	"""
	redirect_field_name = 'redirect_to'
	template_name = 'posts/post.html'
	form_class = PostForm
	option_class = PostOptionForm

# ----------------------------------------------------------------------------------------

class PostView(PostAttrsMixin, LoginRequiredMixin, UloView):
	"""
	Render the post form. See below for upload handler.
	"""

	def post(self, request, *args, **kwargs):

		messages.info(request, _('Enable javascript to make a post.'))
		
		return self.get(request, *args, **kwargs)


	def get_context_data(self, **kwargs):
		
		context = super(PostView, self).get_context_data(**kwargs)
		
		context.update({
		
			'form': self.form_class(), 
			'option0': self.option_class(prefix='option0'),
			'option1': self.option_class(prefix='option1', selected=2)
		
		})
		
		return context

# ----------------------------------------------------------------------------------------

class _PostUploadView(PostAttrsMixin, LoginRequiredMixin, UloFormView):
	"""
	Handle the post request of an image or video. Post requests are first sent to 
	PostImageView or PostVideoView. Once the upload handlers have been set the request 
	is passed to this view for processing.
	"""

	# ID of the new post.
	pid = None


	def get_success_url(self):
		"""
		Redirect to the post detail page.
		"""

		return reverse('posts:detail', args=(self.pid,))


	def get_form_kwargs(self):
		"""
		Make the request object available in the forms.
		"""

		kwargs = super(_PostUploadView, self).get_form_kwargs()
		
		if self.request.method in ('POST', 'PUT'):
		
			kwargs.update({
		
				'request': self.request
		
			})
		
		return kwargs


	@cached_property
	def get_options(self):
		"""
		Return all option forms.
		"""

		return (

			self.option_class(prefix='option0', data=self.request.POST),
			self.option_class(prefix='option1', data=self.request.POST, empty_permitted=True)

		)


	def option_errors(self):
		"""
		Return a dictionary containing the first error found for each option field.
		
		E.g. {'option0': [error], 'option1': [error]}
		"""
		
		errors = {}
		
		messages = []

		for opt in self.get_options:
			
			for item in opt.errors.items():
				
				field, msg = item
				
				messages += msg
				
				break
		
			errors.update({opt.prefix: messages})

		return errors


	def ajax_invalid(self, form):
		"""
		Add the error messages for the option forms to the response.
		"""
		
		data = super(_PostUploadView, self).ajax_invalid(form)
		
		data['errors'].update(self.option_errors())
		
		return data


	def form_valid(self, form):
		"""
		Save the new post and its options.
		"""

		# Get the option forms.
		option0, option1 = self.get_options

		# If the option forms are valid save all components of the post.
		if option0.is_valid() and option1.is_valid():	
			
			try:

				with transaction.atomic():
				
					post = form.save()
					
					option0.save(post=post)
					
					option1.save(post=post)
				

					# Increment the counter that records the number of posts a user has.
					self.request.user.posts_count = F('posts_count')+1
				
					self.request.user.save()


					# Index the post to make it searchable.
					post_search.index_instance(post)


				# Set pid for get_success_url()
				self.pid = post.id
				
				return super(_PostUploadView, self).form_valid(form)

			except Exception as e:

				print(e)

				form.add_post_creation_error()


		# Else display the option form errors to the user.
		return self.form_invalid(form)

# ----------------------------------------------------------------------------------------

class PostMediaAttrsMixin(object):
	"""
	Define the class attributes common to PostImageView and PostVideoView.
	"""

	template_name = 'posts/post.html'
	view_handler = _PostUploadView
	form_class = PostForm


	def get_redirect_url(self):

		return reverse('posts:post')


	def get(self, request, *args, **kwargs):

		if request.is_ajax():

			return JsonResponse(

				{'messages': get_messages_json(request)}, status = 403

			)

		return redirect( self.get_redirect_url() )
	
# ----------------------------------------------------------------------------------------

class PostImageView(PostMediaAttrsMixin, UloUploadView):
	"""
	NOTE: Make sure Django processes the files LAST by making it the last element in the 
	QueryDict. Now if an error is raised because of the file the form data for all other
	fields will remain in the request object.
	"""

	def set_handlers(self, request):

		request.upload_handlers = [
			
			MediaUploadHandler(request=request, images=('file',)),
			MemoryMediaUploadHandler(request=request, images=('file',)),
			TemporaryMediaUploadHandler(request=request, images=('file',))

		]

# ----------------------------------------------------------------------------------------

class PostVideoView(PostMediaAttrsMixin, UloUploadView):
	"""
	NOTE: Make sure Django processes the files LAST by making it the last element in the 
	QueryDict. Now if an error is raised because of the file the form data for all other
	fields will remain in the request object.
	"""

	def set_handlers(self, request):

		request.upload_handlers = [
			
			MediaUploadHandler(request=request, videos=('file',), images=('thumbnail',)),
			MemoryMediaUploadHandler(request=request, videos=('file',), images=('thumbnail',)),
			TemporaryMediaUploadHandler(request=request, videos=('file',), images=('thumbnail',))

		]


# END POST UPLOAD VIEWS
# ----------------------------------------------------------------------------------------




# POST VIEWS
# ----------------------------------------------------------------------------------------

class PostDetailView(UloView):
	"""
	Render a post adding user specific information to the context for a logged in user.
	"""

	template_name = 'posts/post_detail.html'


	def __init__(self, *args, **kwargs):
		"""
		Create a direct connection to the database to perform raw SQL queries.
		"""

		self.cursor = connection.cursor()
		
		return super(PostDetailView, self).__init__(*args, **kwargs)


	def get(self, request, pk, *args, **kwargs):
		"""
		Create a direct connection to the database to perform raw SQL queries.
		"""

		try:

			is_authenticated = request.user.is_authenticated()

			if is_authenticated:

				offset = 6

				self.cursor.execute(
					
					 '''SELECT

							posts_postvote.postoption_id AS vote_id,
					 		post.*

					 	FROM (

						 	SELECT

						 		posts_postoption.id AS option_id,
						 		posts_postoption.colour,
								posts_postoption.text,
								posts_postoption.icon,
								posts_postoption.count,
								post.*

						 	FROM (

							 	SELECT
									
									post.*,
									users_connection.id AS is_following
								
								FROM (

									SELECT

										posts_post.*,
										users_user.name,
										users_user.username,
										users_user.thumbnail AS user_thumbnail,
										users_user.followers_count
									
									FROM posts_post
									
									INNER JOIN users_user 
									
									ON posts_post.user_id=users_user.id
									
									WHERE posts_post.is_active=%s 
									
									AND posts_post.id=%s

								) AS post 

								LEFT JOIN users_connection

								ON post.user_id=users_connection.to_user_id 	
								
								AND users_connection.from_user_id=%s

							) AS post

							LEFT JOIN posts_postoption

							ON post.id=posts_postoption.post_id

						) AS post

						LEFT JOIN posts_postvote

						ON posts_postvote.postoption_id=post.option_id
						
						AND posts_postvote.user_id=%s
						
					''', [True, pk, request.user.id, request.user.id]
				
				)
			
			else:

				offset = 5

				self.cursor.execute(

					 '''SELECT

					 		posts_postoption.id AS option_id,
							posts_postoption.colour,
							posts_postoption.text,
							posts_postoption.icon,
							posts_postoption.count,
							post.*

					 	FROM (
		
							SELECT

								posts_post.*,
								users_user.name,
								users_user.username,
								users_user.thumbnail AS user_thumbnail,
								users_user.followers_count
							
							FROM posts_post
							
							INNER JOIN users_user 
							
							ON posts_post.user_id=users_user.id
							
							WHERE posts_post.is_active=%s 
							
							AND posts_post.id=%s

						) AS post

ulo/templates/posts/post_actions.html
{% extends base_template %}
{% load staticfiles i18n %}


{% block title %}{{ site_name }}{% endblock title %}


{% block css %}
	<link class="css_file" href="{% static 'css/posts/post_actions.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}


{% block content %}
<div id="post_actions">

	<div class="header">
			
		<a class="back" href="{{ back_url }}">
				
			<span class="icon icon_left_arrow"></span>
			<span class="hide">Back to post</span>

		</a>
		
		<h1 class="thin ellipsis">Post actions</h1>

	</div>


	<div class="summary">
		
		<img src="{{ post.thumbnail.url }}">

		<h2 class="thin">{{ post.title }}</h2>
		
	</div>
	

	<ul class="actions_menu">
		
		{% if is_owner %}
		
			<li>

				<a href="{% url 'posts:update' post.id %}">Edit</a>

			</li>

			<li>

				<a href="{% url 'posts:delete' post.id %}">Delete</a>

			</li>
		
		{% else %}
		
			<li>

				<a href="{% url 'posts:report' post.id %}" title="Report">Report</a>

			</li>
		
		{% endif %}
		
	</ul>


</div>
{% endblock content %}

ulo/templates/posts/post_detail.html
{% extends base_template %}
{% load staticfiles i18n ulo_humanise %}


{% block title %}{{ post.title }}{% endblock title %}


{% block css %}
	<link class="css_file" href="{% static 'css/posts/post_detail.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}


{% block content %}
<div id="post_detail">

	<div class="post" data-id="{{ post.id }}" data-user="{{ post.user_id }}">


		<div class="post_media">
	
			<div class="media_container">

				<div class="video_player">

					<video preload="metadata" data-autoplay="true">
						
						<source src="{{ MEDIA_URL }}{{ post.file }}" type="video/mp4">
						Your browser does not support video playback.
							
					</video>

				</div>


				<div class="video_actions cloak">


					<div class="video_track">

						<div class="fragment hide">

							<div class="track_fragment">

								<button class="track_start" data-selector="track_start" type="button">
										
									<span class="pin"></span>

								</button>

								<button class="track_end" data-selector="track_end" type="button">
									
									<span class="pin"></span>

								</button>

							</div>

						</div>

						<div class="track">

							<div class="track_bar">

								<div class="track_range">
								
									<span class="track_buffer"></span>
									<span class="track_progress"></span>
									<span class="track_start"></span>
									<span class="track_end"></span>
									<span class="track_thumbnail" data-src="{{ post.thumbnail }}" style="left: {% widthratio post.thumbnail_time post.duration 100 %}%"></span>
							
								</div>

								<button class="track_slider" type="button"></button>

							</div>

						</div>

					</div>

					<div class="video_controls cf">

						<div class="left">

							<button class="play" type="button">
								
								<span class="play icon icon_play_white"></span>

							</button>

							<button class="loop" type="button" title="Loop">
								
								<span class="loop icon icon_loop"></span>

							</button>

						</div>

						<div class="video_time">

							<span class="current_time">0:00</span>&nbsp;/&nbsp;
							<span class="duration">0:00</span>

						</div>

						<div class="right">

							<div class="volume_container">
								
								<div class="volume_bar">

									<div class="volume_range">

										<div class="volume_level">
											
											<span class="volume_value"></span>

											<button class="volume_slider" type="button"></button>

										</div>
										

									</div>

								</div>

								<button class="volume" type="button">
									
									<span class="volume icon icon_volume_white"></span>

								</button>

							</div>

							<button class="fullscreen" type="button">
								
								<span class="icon icon_expand_white"></span>

							</button>

						</div>

					</div>

				</div>

			</div>

		</div>
		<!-- END .post_media -->


		<div class="post_data cf">

			<div class="main_panel_container">

				<div class="main_panel">
						
					<div class="post_info">

						<div class="table">

							<div class="cell">

								<h1 class="post_title thin">{{ post.title }}</h1>

							</div>

							{% if post.description != '' or post.category != None %}
							<div id="toggle_post_description" class="cell">

								<button type="button" data-toggle="post_description" title="Description" data-touch="local">

									<span class="icon icon_down_arrow"></span>
									<span class="hide">Description</span>

								</button>

							</div>
							{% endif %}

						</div>

						{% if post.description != '' or post.category != None %}
						
						<div id="post_description">

							{% if post.description != '' %}
							<p class="description">{{ post.description }}</p>
							{% endif %}

							{% if post.category != None %}
							<span class="category">{{ post.category }}<span>
							{% endif %}

						</div>

						{% endif %}

						<div class="post_meta">
				
							<span class="published ellipsis">{{ post.published|short_date }}</span>
							<span class="views ellipsis">1,000,00{{ post.views }}&nbsp;view{% if post.views != 1 %}s{% endif %}</span>
						
						</div>

					</div>




					<div class="post_actions post_panel">

						<form class="post_vote_form" action="{% url 'posts:vote' post.id %}" method="get">
				
						{% for option in post.options %}<div class="vote">

							{% if option.vote_id == None %}
							
								<button class="vote" name="vote" value="{{ option.option_id }}" type="submit" title="{{ option.text }}">

									<span {% if option.icon == '' %}class="vote_icon" style="background-color:{{ option.colour }}"{% else %}class="vote_icon font_icon {{ option.icon }}"{% endif %}></span>

									<div class="vote_data">

										<span class="vote_text bold ellipsis">{{ option.text }}</span>
										<span class="vote_count abbr_count ellipsis">{{ option.count|abbreviate }}</span>
										<span class="full_count">{{ option.count }}</span>

									</div>

								</button>
							
							{% else %}

								<input name="voted" type="hidden" value="{{ option.vote_id }}">

								<button class="vote selected" name="vote" value="{{ option.option_id }}" type="submit" title="{{ option.text }}">

									<span {% if option.icon == '' %}class="vote_icon" style="background-color:{{ option.colour }}"{% else %}class="vote_icon font_icon {{ option.icon }}"{% endif %}></span>

									<div class="vote_data">

										<span class="vote_text bold ellipsis">{{ option.text }}</span>
										<span class="abbr_count ellipsis">{{ option.count|abbreviate }}</span>
										<span class="full_count">{{ option.count }}</span>

									</div>

								</button>

							{% endif %}
			
							</div>{% endfor %}
				
						</form>

						<a class="toggle_actions_menu" href="{% url 'posts:actions' post.id %}" title="Post actions" data-toggle="post_menu" data-id="{{ post.id }}"{% if is_owner %} data-is-owner="true"{% endif %}>

							<span class="icon icon_menu"></span>
							<span class="hide">Post actions</span>
						
						</a>

					</div>


					<div class="post_user post_panel">
	
						{% if is_owner == False %}

						<div class="user_actions">	
						
							{% if post.is_following == None %}
						
							<a class="connect follow" href="{% url 'users:follow' post.user_id %}" title="Follow">

								<span class="full_count">{{ post.followers_count }}</span>
								<span class="abbr_count bold">{{ post.followers_count|abbreviate }}</span>
								<span class="icon icon_follow"></span>
								
							</a>
						
							{% else %}
						
							<a class="connect unfollow" href="{% url 'users:unfollow' post.user_id %}" title="Unfollow">

								<span class="full_count">{{ post.followers_count }}</span>
								<span class="abbr_count bold">{{ post.followers_count|abbreviate }}</span>
								<span class="icon icon_unfollow_white"></span>
							
							</a>
						
							{% endif %}
							
						</div>
						{% endif %}
					
						<div class="user_profile">

							<a href="{% url 'users:profile' post.username %}" class="profile" data-apl="true" title="{{ post.name }}">
						
								<img class="user_thumbnail" src="{{ MEDIA_URL }}{{ post.user_thumbnail }}">

								<div class="user_names">
									
									<h2 class="name thin ellipsis">{{ post.name }}</h2>
									<span class="username ellipsis">@{{ post.username }}</span>
									
								</div>

							</a>

						</div>

					
					</div>



					{% if comments_disabled == False %}

					<div class="post_comment">
						
						<span class="comments_count">
							{{ post.comments_count }}&nbsp;comment{% if post.comments_count != 1 %}s{% endif %}
						</span>

						<form id="comment_form" action="{% url 'posts:comment' post.id %}" method="post">

							{% csrf_token %}

							{{ form.comment }}
						
						</form>

						<div id="comments_container">

							<noscript>
								<p class="javascript_disabled">
									Enable javascript to load comments for this post.
								</p>
							</noscript>

						</div>

						{% if post.comments_count != 0 %}
						<button id="load_comments" data-action="{% url 'posts:comment_load' post.id %}" type="button">
							Load comments
						</button>
						{% endif %}

					</div>

					{% else %}

					<div id="comments_container">

						<p class="comments_disabled">Comments have been disabled for this post.</p>

					</div>

					{% endif %}



				</div>

			</div>


			<div class="side_panel">

				<span class="panel_divider"></span>

				<div class="advertisements">

					<img src="https://s1.2mdn.net/viewad/4157372/UK_MakeIt_300x250.jpg">
				
				</div>

			</div>


		</div>
		<!-- END .post_data -->


	</div>
	<!-- END .post -->



	{% if timeline == False %}

		<!-- POST ACTIONS MENU -->
		<div id="post_menu" class="actions_menu">
			
			<ul>

				<span class="user">
			
					<li class="action">
					
						<button class="report_post" type="button">Report</button>
					
					</li>

				</span>

				<span class="owner">
			
					<li class="action">
					
						<button class="edit_post" type="button">Edit</button>
					
					</li>

					<li class="action">
					
						<button class="delete_post" type="button" data-page="detail">Delete</button>
					
					</li>

				</span>
			
			</ul>
		
		</div>
		<!-- END POST ACTIONS MENU -->


		{% if post.comment_settings != comments_disabled %}

		<!-- COMMENT ACTIONS MENU -->
		<div id="comment_menu" class="actions_menu">
		
			<ul>

				<span class="user">
				
					<li class="action">
					
						<button class="report_comment" type="button">Report</button>
					
					</li>
				
				</span>

				<span class="owner">
				
					<li class="action">
					
						<button class="delete_comment" type="button">Delete</button>
					
					</li>
				
				</span>

			</ul>
		
		</div>
		<!-- END COMMENT ACTIONS MENU -->
		
		{% endif %}


	{% endif %}

</div>
{% endblock content %}

{% block js %}
	<script class="js_file" src="{% static 'js/users/utils.js' %}"></script>
	<script class="js_file" src="{% static 'js/posts/post_detail.js' %}"></script>
{% endblock js %}

ulo/templates/posts/post_report.html
{% extends base_template %}
{% load staticfiles i18n %}


{% block title %}Report{% endblock title %}


{% block css %}
	<link class="css_file" href="{% static 'css/posts/post_report.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}


{% block content %}
<div id="post_report">

	<div class="centre" data-close-pip="true">

		<div class="wrapper{% if request.is_ajax == False %} fill{% endif %}">

			<div class="header">

				{% if request.is_ajax %}

				<span class="back icon icon_cross" data-close-pip="true"></span>

				{% else %}

				<a class="back" href="{% url 'posts:actions' form.post_id %}" title="Back to post actions">
										
					<span class="icon icon_left_arrow"></span>

					<span class="hide">Back to post actions</span>
				
				</a>

				{% endif %}
				
				<h1 class="thin ellipsis">Report this post</h1>
			
			</div>


			{% if request.is_ajax == False %}

			<div class="summary">

				<img src="{{ form.post.thumbnail.url }}">
				
				<h2 class="thin">{{ form.post.title }}</h2>

			</div>

			{% endif %}


			<form id="post_report_form" action="{% url 'posts:report' form.post_id %}"  method="post">
				
				{% csrf_token %}
				
				{{ form.pip }}


				{% if form.non_field_errors %}
				<div id="post_report_form_errors" class="form_errors">

					{% for error in form.non_field_errors %}
					<p class="validation error">{{ error }}</p>
					{% endfor %}

				</div>
				{% endif %}


				<div class="field">

					<p class="help_text bold">{{ form.issue.help_text }}</p>

					<div id="issue_container">

						{% for error in form.issue.errors %}
							<p class="validation error">{{ error }}</p>
						{% endfor %}

						{{ form.issue }}
					
					</div>

				</div>
				

				<div class="field">

					<p class="help_text bold">{{ form.information.help_text }}</p>

					<div id="information_container">

						{% for error in form.information.errors %}
							<p class="validation error">{{ error }}</p>
						{% endfor %}

						<div class="text_field">{{ form.information }}</div>
					
					</div>

				</div>


				<div class="submit_container">

					<input id="post_report_submit" name="submit" type="submit" value="Report">
				
				</div>


			</form>

		</div>

	</div>

</div>
{% endblock content %}


{% block js %}
	<script class="js_file" src="{% static 'js/posts/post_report.js' %}"></script>
{% endblock js %}

ulo/templates/posts/post_report_complete.html
{% extends base_template %}
{% load staticfiles i18n %}


{% block title %}Report Complete{% endblock title %}

{% block css %}
	<link class="css_file" href="{% static 'css/posts/post_report_complete.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}


{% block content %}
<div id="post_report_complete">

	<div class="centre" data-close-pip="true">
		
		<div class="wrapper">

			<div class="header">
				
				{% if request.is_ajax == True %}

				<h1 class="spacing">Thank you for your report</h1>

				<button class="icon icon_cross" type="button" data-close-pip="true">
				
					<span class="hide">Close</span>
				
				</button>

				{% else %}

				<h1>Thank you for your report</h1>

				{% endif %}
			
			</div>
			
			<p>
				If we find the content to be in violation of our rules, we will take the necessary course of action.
			</p>

		</div>

	</div>

</div>
{% endblock content %}