ulo/accounts/urls.py
"""
Accounts URL Configuration
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	# Email verification
	url(r'^verification/(?P<token>[^<>\'"@]+)/$',
		views.EmailVerificationView.as_view(), name='verification'),
	url(r'^resend_verification/$',
		views.ResendEmailVerificationView.as_view(), name='resend_verification'),


	# Password reset
	url(r'^password_reset/$', 
		views.PasswordResetBeginView.as_view(), name='password_reset_begin'),
	url(r'^password_reset/email/$', 
		views.PasswordResetEmailView.as_view(), name='password_reset_email'),
	url(r'^password_reset/sent/$', 
		views.PasswordResetSentView.as_view(), name='password_reset_sent'),
	url(r'^password_reset/(?P<token>[^<>\'"@]+)/$', 
		views.PasswordResetView.as_view(), name='password_reset'),


	# Not my account
	url(r'^not_my_account/confirmed/$',
		views.NotMyAccountConfirmedView.as_view(), name='not_my_account_confirmed'),
	url(r'^not_my_account/$',
		views.NotMyAccountNoUserView.as_view(), name='not_my_account_no_user'),
	url(r'^not_my_account/(?P<token>[^<>\'"@]+)/$',
		views.NotMyAccountView.as_view(), name='not_my_account'),


	# Token expired
	url(r'^token_expired/$', views.TokenExpiredView.as_view(), name='token_expired'),
	

	# Account Deactivation.
	url(r'^deactivate/$', views.DeactivateAccountView.as_view(), name='deactivate'),
	url(r'^deactivated/$', views.DeactivatedAccountView.as_view(), name='deactivated')

]

# ----------------------------------------------------------------------------------------

ulo/config/urls.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports

# Core django imports
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

# Thrid party app imports

# Project imports
from pages.views import HomeAuthView, NavigationView
from users.views import SignUpView, LoginView, LogoutView

# ----------------------------------------------------------------------------------------


# TO SERVE MEDIA FILES IN DEVELOPMENT ONLY
from django.conf.urls.static import static

# ----------------------------------------------------------------------------------------

urlpatterns = [

	# PAGES APP

	url(r'^$', HomeAuthView.as_view(), name='home'),

	# Site navigation when js is disabled.
	url(r'^navigation/$', NavigationView.as_view(), name='navigation'),


	# SEARCH APP

	url(r'^search/', include('search.urls', namespace='search')),


	# POSTS APP

	url(r'^post/', include('posts.urls', namespace='posts')),


	# USERS APP

	url(r'^user/', include('users.urls', namespace='users')),

	url(r'^signup/$', SignUpView.as_view(), name='signup'),

	url(r'^login/(\?redirect_to=(?P<redirect_to>[^<>\'"@]*/))?$', LoginView.as_view(), name='login'),
	
	url(r'^logout/$', LogoutView.as_view(), name='logout'),


	# COMMENTS APP

	url(r'^comment/', include('comments.urls', namespace='comments')),


	# ACCOUNTS APP
	
	url(r'^accounts/', include('accounts.urls', namespace='accounts')),


	# SETTINGS APP

	url(r'^settings/', include('settings.urls', namespace='settings')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ----------------------------------------------------------------------------------------

ulo/posts/urls.py
"""
Posts URL Configuration
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	# Post form
	url(r'^$', views.PostView.as_view(), name='post'),

	# Post detail page
	url(r'^(?P<pk>[\d]+)/$', views.PostDetailView.as_view(), name='detail'),

	# Post vote
	url(r'^(?P<pk>[\d]+)/vote/$', views.PostVoteView.as_view(), name='vote'),

	# Image post handler
	url(r'^image/$', views.PostImageView.as_view(), name='image'),
	
	# Video post handler
	url(r'^video/$', views.PostVideoView.as_view(), name='video'),

	# Comment
	url(r'^(?P<pk>[\d]+)/comment/$', views.PostCommentView.as_view(), name='comment'),
	url(r'^(?P<pk>[\d]+)/comment/load/$', views.PostCommentLoadView.as_view(), name='comment_load'),

	# Update post
	url(r'^(?P<pk>[\d]+)/update/$', views.PostUpdateView.as_view(), name='update'),
	
	# Delete post
	url(r'^(?P<pk>[\d]+)/delete/$', views.PostDeleteView.as_view(), name='delete'),

	# Report post
	url(r'^(?P<pk>[\d]+)/report/$', views.PostReportView.as_view(), name='report'),
	url(r'^report/complete/$', views.PostReportCompleteView.as_view(), name='report_complete'),

	# Post actions menu (JS disabled)
	url(r'^(?P<pk>[\d]+)/actions/$', views.PostActionsView.as_view(), name='actions'),

]

# ----------------------------------------------------------------------------------------

ulo/settings/urls.py
"""
Settings URL Configuration
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	url(r'^account/$', views.AccountSettingsView.as_view(), name='account'),

	url(r'^password/$', views.PasswordSettingsView.as_view(), name='password'),

	# url(r'^notifications/$',
	# 	views.NotificationSettingsView.as_view(), name='notifications'),
]

# ----------------------------------------------------------------------------------------

ulo/users/urls.py
"""
Users URL Configuration
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	url(r'^available/(?P<username>[\w]+)/$', views.UsernameAvailableView.as_view(), name='available'),
		
	# Follow user
	url(r'^follow/(?P<pk>[\d]+)/$', views.FollowUserView.as_view(), name='follow'),
	
	# UnFollow user
	url(r'^unfollow/(?P<pk>[\d]+)/$', views.UnFollowUserView.as_view(), name='unfollow'),


	# Update profile information
	url(r'^update/$', views.ProfileUpdateView.as_view(), name='profile_update'),

	# Update profile picture
	url(r'^(?P<pk>[\d]+)/image/update/$', views.ProfileUpdateImageView.as_view(), name='profile_update_image'),

	# Delete profile picture
	url(r'^(?P<pk>[\d]+)/image/delete/$', views.ProfileDeleteImageView.as_view(), name='profile_delete_image'),


	# Profile page - posts tab
	url(r'^(?P<username>[\w]+)/$', views.ProfileView.as_view(), name='profile'),

	# Profile page - followers tab
	url(r'^(?P<username>[\w]+)/followers/$', views.ProfileFollowersView.as_view(), name='followers'),
	
	# Profile page - following tab
	url(r'^(?P<username>[\w]+)/following/$', views.ProfileFollowingView.as_view(), name='following'),

]

# ----------------------------------------------------------------------------------------

ulo/users/forms.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals
import os, re

# Core django imports
from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.password_validation import validate_password
from django.db import transaction
from django.utils.crypto import get_random_string
from django.utils.translation import ugettext_lazy as _

# Thrid party app imports

# Project imports
from .search import user_search
from .widgets import ProfileUpdateDOBWidget, SignUpDOBWidget
from emails.emails import verify_email
from ulo.fields import PasswordField, UloDOBField, UloPIPField
from ulo.formmixins import CleanUsernameMixin, DeleteFileMixin, UploadFileMixin
from ulo.forms import UloForm, UloModelForm
from ulo.utils import reserved_usernames

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

USERS_MIN_AGE = 13

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

class SignUpForm(CleanUsernameMixin, UloModelForm):

	# Auto generated username.
	generated_username = None

	# Use custom PasswordField for additional validation
	password = PasswordField( label=_('Password'), )
	
	# Use custom Widget to list dates in a drop down select menu
	dob = UloDOBField(

		label=_('Birthday'), 
		localize=True, 
		min_age=USERS_MIN_AGE, 
		widget=SignUpDOBWidget

	)


	class Meta:
		
		model = get_user_model()
		
		fields = ('name', 'email', 'password', 'dob',)
		
		localized_fields = ('dob',)
		
		widgets = {

			'name': forms.TextInput(attrs={'autofocus': 'autofocus'})

		}

		error_messages = {

			'email': {

				'invalid': _('Please enter a valid email address.')

			}

		}


	def __init__(self, *args, **kwargs):
		"""
		
		Set form field attributes.
		
		"""

		kwargs['auto_id'] = 'signup_%s'

		super(SignUpForm, self).__init__(*args, **kwargs)

		for i, field in self.fields.items():
			
			field.widget.attrs.update({

				'placeholder': _(field.label),
				'autocomplete': 'off',
				'class': 'box_border'
			
			})


	def add_account_creation_error(self):

		self.add_error(

			None,
			_('Sorry, it looks like we failed to create your account. Please try again.')

		)


	def is_valid(self):
		"""

		NOTE Delete this function and add 'username' to Meta.fields to have the
		user create their own username when signing up.

		"""
		valid = super(SignUpForm, self).is_valid()

		if valid == True:

			try:
			
				self.generated_username =  self.auto_username()
			
			except forms.ValidationError as e:

				valid = False


		return valid


	def auto_username(self, max_length=30):
		"""
		
		Return a unique username generate from the user's name or email. Raise a
		ValidationError if no username was generated.

		@param max_length: max length of the username.

		"""

		pattern = r'\w+'

		name = self.cleaned_data.get('name', '')

		username = 	''.join(re.findall(pattern, name, re.I))[:max_length]


		if username == '':

			name = self.cleaned_data.get('email', '').split('@', 1)[0]
		
			username = ''.join(re.findall(pattern, name, re.I))[:max_length]


		if username == '':

			length = 16

			allowed_chars='abcdefghijklmnopqrstuvwxyz0123456789'
		
			username = get_random_string(length=length, allowed_chars=allowed_chars)

		
		username = username.lower()
		
		username_copy = username
		
		attempt, max_attempt, length = 0, 5, 5


		while attempt < max_attempt:

			if get_user_model().objects.filter(username=username).exists() or \
				username in reserved_usernames:

				attempt = attempt+1

				if attempt >= max_attempt:

					self.add_account_creation_error()

					raise forms.ValidationError(

						'Auto generate username error', code='auto_username'

					)

				username = (

					username_copy[:max_length-length] + 

					get_random_string(length=length, allowed_chars='0123456789')
				
				)

				length = length+1

			else:

				attempt = max_attempt

		return username.lower()


	def clean_password(self):
		"""
		
		Create a user instance from the USER_ATTRIBUTES fields. This will create a 
		user with only the fields required to run UserAttributeSimilarityValidator which 
		tests the password for similarities with the user's personal information.

		"""
		
		attrs = settings.USER_ATTRIBUTES
		
		user_params = {}
		
		for attr in attrs:

			user_params[attr] = self.cleaned_data.get(attr)
		
		user = get_user_model()(**user_params)
		

		password = self.cleaned_data.get('password')
		
		# Run the validator(s) defined in the settings file (base.py)
		validate_password(password=password, user=user)
		
		user = None

		return password


	def save(self, commit=True):
		"""

		Save the form data to the database, storing a hashed version of the
		user's password and send an email confirmation email to the user.

		"""

		user = super(SignUpForm, self).save(commit=False)
		
		user.set_password(self.cleaned_data['password'])

		user.username = self.generated_username


		if commit:

			# Will raise an exception if save() or index_instance() fails.

			with transaction.atomic():

				user.save()

				user_search.index_instance(user)


			verify_email(user)


		return user

# ----------------------------------------------------------------------------------------

class LoginForm(UloForm):

	# Indicates if this form has been loaded within another page.
	pip = UloPIPField(id='login_pip')

	# Email Address
	email = forms.EmailField(
		
		label=_('Email address'),
		
		widget=forms.TextInput(attrs={
			
			'class': 'box_border',
			'autofocus': 'autofocus',
			'placeholder': _('Email address'),
			'required': 'required',
		
		}),
	)

	# Password - PasswordField performs its own validation.
	password = PasswordField(
		
		label=_('Password'),
		
		widget=forms.PasswordInput(attrs={
			
			'class': 'box_border',
			'placeholder': _('Password'),
			'required': 'required',
		
		}),
	
	)

	# Determines when the session should expire
	remember = forms.BooleanField(
	
		label=_('Remember me'),
	
		required=False,
	
	)

	# Redirect path
	redirect_to = forms.CharField(
		
		widget=forms.HiddenInput(),

		required = False
	
	)


	def __init__(self, redirect_to=None, *args, **kwargs):
		"""
		Store a reference to the authenticated user and prefix all IDs with the 
		value 'login_'
		"""

		kwargs['auto_id'] = 'login_%s'

		super(LoginForm, self).__init__(*args, **kwargs)


	def add_login_error(self, msg=None):

		# Remove all field specific error messages.
		self.errors.clear()

		# Add a single non field error message.
		self.add_error(None, msg or _('The email address and password do not match.'))

# ----------------------------------------------------------------------------------------

class ProfileUpdateForm(UloModelForm):

	# DateField that checks the user's age is gte min_age
	dob = UloDOBField(label=_('Birthday'), min_age=USERS_MIN_AGE, widget=ProfileUpdateDOBWidget)

	
	class Meta:
		
		model = get_user_model()
		
		fields = ('location', 'dob', 'blurb', 'gender')

		widgets = {

			'blurb': forms.Textarea()

		}


	def __init__(self, *args, **kwargs):

		super(ProfileUpdateForm, self).__init__(*args, **kwargs)

		for i, field in self.fields.items():
			
			field.widget.attrs.update({

				'autocomplete': 'off',
				'class': 'box_border'
			
			})


	def add_account_update_error(self):

		self.add_error(

			None,
			_('Sorry, it looks like we failed to update your account. Please try again.')

		)


	def save(self, commit=True):
		"""

		Update user instance.

		"""

		# Will raise an exception if save() or update_instance() fails.

		with transaction.atomic():

			user = super(ProfileUpdateForm, self).save(commit=commit)
		
			if commit:

				user_search.update_instance(user)


		return user

# ----------------------------------------------------------------------------------------

class ProfileUpdateImageForm(DeleteFileMixin, UploadFileMixin, UloModelForm):
	"""
	Display a form the upload/change the user's profile picture.
	"""

	class Meta:

		model = get_user_model()
		
		fields = ('photo', 'thumbnail')
		
		widgets = {

			'photo': forms.ClearableFileInput(attrs={
			
				'accept': 'image/gif,image/jpeg,image/jpg,image/png',
				'capture': 'capture',
				'class': 'file'
			
			}),
			
		}

		error_messages = {

			'photo': {

				'missing': _('Please upload a photo.')

			}

		}


	def __init__(self, *args, instance=None, **kwargs):
		"""
		Initialise the mixins.
		"""

		# UploadFileMixin - file field name.
		kwargs['ufile'] = 'photo'

		# DeleteFileMixin - files to delete.
		self.store_paths(instance, 'photo', 'thumbnail')

		super(ProfileUpdateImageForm, self).__init__(*args, instance=instance, **kwargs)


	def add_account_photo_error(self):

		self.add_error(

			None,
			_('Sorry, it looks like we failed to update your photo. Please try again.')

		)


	def save(self, commit=True):
		"""

		Update the user's profile photo.
		
		"""

		# Will raise an exception if save() or update_instance() fails.

		with transaction.atomic():

			user = super(ProfileUpdateImageForm, self).save(commit=commit)

			if commit:

				user_search.update_instance( user )


		if commit:

			self.delete_files(user)


		return user

# ----------------------------------------------------------------------------------------

ulo/templates/users/profile.html
{% extends base_template %}
{% load staticfiles i18n ulo_humanise %}


{% block title %}{{ profile.name }} @{{ profile.username }}{% endblock title %}

{% block css %}

	{% if is_owner %}
	<link class="css_file" href="{% static 'css/uploads/upload.css' %}" rel="stylesheet" type="text/css">
	{% endif %}
	<link class="css_file" href="{% static 'css/users/profile.css' %}" rel="stylesheet" type="text/css">
	
{% endblock css %}

{% block content %}
<div id="profile" data-user-id="{{ profile.id }}">

	<div class="profile_header">
		<div class="container box_border">
			

			<div class="cf">

				<div id="profile_picture">
					
					<div class="animation">
						
						<div class="one"></div>
						<div class="two"></div>
						<div class="three"></div>

					</div>

					<img src="{{ MEDIA_URL }}{{ profile.photo }}">

					{% if is_owner %}

					<div id="picture_actions">

						<span class="caret_up"></span>

						<ul class="picture_menu">
							<li>
								<div class="button change_picture">
									Change
									<input accept="image/gif,image/jpeg,image/jpg,image/png" capture="capture" class="file" id="picture" name="picture" type="file">
								</div>
							</li>
							
							<li>
								<button class="button delete_picture" type="button">Delete</button>
							</li>

						</ul>

					</div>

					{% endif %}

				</div>

				<div id="profile_information">

					<div class="profile_actions">

					{% if is_owner %}
					
						<a class="edit_profile" data-apl="true" href="{% url 'users:profile_update' %}" title="Edit Profile">
							<span class="icon icon_edit"></span
							><span class="text lrg">Edit</span>
						</a>
					
					{% else%}
							
						{% if is_following %}

							<a class="connect unfollow" href="{% url 'users:unfollow' profile.id %}" title="Unfollow">
								<span class="icon icon_unfollow_white"></span
								><span class="text lrg">Unfollow</span>
							</a>
						
						{% else %}
						
							<a class="connect follow" href="{% url 'users:follow' profile.id %}" title="Follow">
								<span class="icon icon_follow"></span
								><span class="text lrg">Follow</span>
							</a>
						
						{% endif %}

					{% endif %}

					</div>

					<div class="profile_names">
					
						<h1 class="thin ellipsis">{{ profile.name }}</h1>
						<span class="username ellipsis">@{{ profile.username }}</span>
					
					</div>


					{% if profile.blurb != '' %}

					<p class="blurb">{{ profile.blurb }}</p>
					
					{% endif %}


					{% if profile.location != '' %}
					
					<p class="location">
						
						<div class="location_icon">
							
							<span class="icon icon_location"></span>

						</div>
					
						{{ profile.location }}

					</p>

					{% endif %}

				</div>

			</div>


			<div id="profile_tabs">

				{% if tab == 'posts' %}

				<a id="posts" class="tab selected" href="{% url 'users:profile' profile.username %}" title="Posts">
					
					<span class="full_count">{{ profile.posts_count }}</span>
					<span class="abbr_count bold">{{ profile.posts_count|abbreviate }}</span>
					<span class="text">posts</span>
				
				</a>
				
				<a id="followers" class="tab" href="{% url 'users:followers' profile.username %}" title="Followers">
					
					<span class="full_count">{{ profile.followers_count }}</span>
					<span class="abbr_count bold">{{ profile.followers_count|abbreviate }}</span>
					<span class="text">followers</span>
					
				</a>
				
				<a id="following" class="tab" href="{% url 'users:following' profile.username %}" title="Following">
					
					<span class="full_count">{{ profile.following_count }}</span>
					<span class="abbr_count bold">{{ profile.following_count|abbreviate }}</span>
					<span class="text">following</span>
					
				</a>

				{% elif tab == 'followers' %}

				<a id="posts" class="tab" href="{% url 'users:profile' profile.username %}" title="Posts">
					
					<span class="full_count">{{ profile.posts_count }}</span>
					<span class="abbr_count bold">{{ profile.posts_count|abbreviate }}</span>
					<span class="text">posts</span>
				
				</a>
				
				<a id="followers" class="tab selected" href="{% url 'users:followers' profile.username %}" title="Followers">
					
					<span class="full_count">{{ profile.followers_count }}</span>
					<span class="abbr_count bold">{{ profile.followers_count|abbreviate }}</span>
					<span class="text">followers</span>
					
				</a>
				
				<a id="following" class="tab" href="{% url 'users:following' profile.username %}" title="Following">
					
					<span class="full_count">{{ profile.following_count }}</span>
					<span class="abbr_count bold">{{ profile.following_count|abbreviate }}</span>
					<span class="text">following</span>
					
				</a>

				{% else %}

				<a id="posts" class="tab" href="{% url 'users:profile' profile.username %}" title="Posts">
					
					<span class="full_count">{{ profile.posts_count }}</span>
					<span class="abbr_count bold">{{ profile.posts_count|abbreviate }}</span>
					<span class="text">posts</span>
				
				</a>
				
				<a id="followers" class="tab" href="{% url 'users:followers' profile.username %}" title="Followers">
					
					<span class="full_count">{{ profile.followers_count }}</span>
					<span class="abbr_count bold">{{ profile.followers_count|abbreviate }}</span>
					<span class="text">followers</span>
					
				</a>
				
				<a id="following" class="tab selected" href="{% url 'users:following' profile.username %}" title="Following">
					
					<span class="full_count">{{ profile.following_count }}</span>
					<span class="abbr_count bold">{{ profile.following_count|abbreviate }}</span>
					<span class="text">following</span>
					
				</a>


				{% endif %}

			</div>

			
		</div>
	</div>


	<div id="tab_content" class="container box_border">

		{% if tab == 'posts' %}

		<div id="posts_tab">

			<div class="content">

			{% for post in tab_data %}

				<div class="item">

					<div class="spacing">

						<a class="post_thumbnail" href="{% url 'posts:detail' post.cid %}" data-apl="true">

							<img src="{{ MEDIA_URL }}{{ post.thumbnail }}">

						</a>
							
						<div class="post_data">
							
							<a class="title bold" href="{% url 'posts:detail' post.cid %}" data-apl="true" title="{{ post.title }}">
								<span class="text">{{ post.title }}</span>

							</a>
							
							<div class="post_meta">
								
								<span class="published">{{ post.published|elapsed_time }}</span>

								{% if post.views != None %}
								<span class="views">{{ post.views }}&nbsp;view{% if post.views != 1 %}s{% endif %}</span>
								{% endif %}
							
							</div>
						
						</div>

					</div>
					
				</div>

			{% empty %}

				<div class="empty">

					{% if is_owner %}

						<p>Create your first <a class="bold" data-apl="true" href="{% url 'posts:post' %}">post.</a></p>
					
					{% else %}
					
						<p>@{{ profile.username }} has no posts.</p>
					
					{% endif %}
				
				</div>

			{% endfor %}

			</div>

			{% if has_next %}

			<div class="load">

				<a class="load_posts load" href="{{ request.path_info }}?max_id={{ max_id }}">
					Next Page
				</a>
			
			</div>
			
			{% endif %}

		</div>

		{% elif tab == 'followers' %}

		<div id="followers_tab">

			<div class="content">

			{% for follower in tab_data %}

				<div class="item">

					<div class="spacing">

						{% if follower.is_following != None %}
							
							<div class="connection_actions">

								<a class="connect unfollow" href="{% url 'users:unfollow' follower.id %}" title="Unfollow">
									<span class="icon icon_unfollow_white"></span
									><span class="text lrg">Unfollow</span>
								</a>

							</div>

						{% elif user.pk == None or follower.id != user.pk %}
							
							<div class="connection_actions">

								<a class="connect follow" href="{% url 'users:follow' follower.id %}" title="Follow">
									<span class="icon icon_follow"></span
									><span class="text lrg">Follow</span>
								</a>

							</div>

						{% endif %}

						<div class="connection_user">

							<a href="{% url 'users:profile' follower.username %}" data-apl="true">

								<img src="{{ MEDIA_URL }}{{ follower.thumbnail }}">

								<div class="connection_names">
									<h4>{{ follower.name }}</h4>
									<span>@{{ follower.username }}</span>
								</div>

							</a>

						</div>

					</div>
					
				</div>

			{% empty %}

				<div class="empty">

					{% if is_owner %}

						<p>You have no followers.</p>
					
					{% else %}
					
						<p>@{{ profile.username }} has no followers.</p>
					
					{% endif %}
				
				</div>

			{% endfor %}

			</div>

			{% if has_next %}
			<div class="load">

				<a class="load_followers load" href="{{ request.path_info }}?max_id={{ max_id }}">
					Next Page
				</a>
			
			</div>
			{% endif %}

		</div>

		{% else %}

		<div id="following_tab">

			<div class="content">

			{% for following in tab_data %}

				<div class="item">

					<div class="spacing">

						{% if is_owner or following.is_following != None %}
							
							<div class="connection_actions">

								<a class="connect unfollow" href="{% url 'users:unfollow' following.id %}" title="Unfollow">
									<span class="icon icon_unfollow_white"></span
									><span class="text">Unfollow</span>
								</a>

							</div>

						{% elif following.id != user.pk %}
							
							<div class="connection_actions">

								<a class="connect follow" href="{% url 'users:follow' following.id %}" title="Follow">
									<span class="icon icon_follow"></span
									><span class="text">Follow</span>
								</a>

							</div>

						{% endif %}


						<div class="connection_user">

							<a href="{% url 'users:profile' following.username %}" data-apl="true">

								<img src="{{ MEDIA_URL }}{{ following.thumbnail }}">

								<div class="connection_names">

									<h4 class="ellipsis">{{ following.name }}</h4>
									<span class="ellipsis">@{{ following.username }}</span>
								
								</div>

							</a>

						</div>


					</div>
					
				</div>

			{% empty %}
				
				<div class="empty">
					
					{% if is_owner %}
					
						<p>You are not following anyone.</p>
					
					{% else %}
						
						<p>@{{ profile.username }} is not following anyone.</p>
					
					{% endif %}
				
				</div>
			
			{% endfor %}

			</div>

			{% if has_next %}
			<div class="load">

				<a class="load_following load" href="{{ request.path_info }}?max_id={{ max_id }}">
					Next Page
				</a>

			</div>
			{% endif %}

		</div>

		{% endif %}

	</div>

</div>


{% if is_owner %}
<div id="editor_container" class="hide modal box_border">
	<div id="editor">


		<div id="editor_header">
		
			<h2 class="ellipsis">Editor</h2>

			<button id="editor_close" class="icon icon_cross" type="button" data-close-modal="true">
				<span class="hide">Close editor</span>
			</button>
		
		</div>


		<div id="editor_body">
			
			<span class="overlay disabled"></span>

			<div id="editor_content"></div>
		
		</div>


		<div id="editor_footer">
			
			<div id="scale_element">

				<div class="editor_slider">

					<button class="slider scale_slider" type="button">
						
						<span class="hide">Scale</span>

					
					</button>

					<span class="slider_track">
						
						<span class="trail"></span>

					</span>

				</div>
				
			</div>

			<div class="editor_actions">

				<button id="editor_submit" type="button">
					Change
				</button><div id="editor_input" class="file_input">
						
					<span class="icon icon_camera_white"></span>
					<input accept="image/gif,image/jpeg,image/jpg,image/png" capture="capture" class="file" name="editor_photo" type="file">

				</div>

			</div>

		</div>


		<div id="editor_menu">

			<button id="toggle_editor_menu_actions" type="button" class="toggle_menu" data-toggle="editor_menu_actions">
				<span class="icon icon_down_arrow_white"></span>
				<span class="hide">Editor menu</span>
			</button>

			<div id="editor_menu_actions" class="hide">

				<button class="editor_delete" type="button">
					Delete
				</button>

			</div>

		</div>


	</div>

</div>
{% endif %}

{% endblock content %}


{% block js %}

	<script class="js_file" src="{% static 'js/users/utils.js' %}"></script>
	<script class="js_file" src="{% static 'js/users/profile.js' %}"></script>

{% endblock js %}