ulo/accounts/urls.py
"""
Accounts URL Configuration
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	# Email verification
	url(r'^verification/(?P<token>[^<>\'"@]+)/$',
		views.EmailVerificationView.as_view(), name='verification'),
	url(r'^resend_verification/$',
		views.ResendEmailVerificationView.as_view(), name='resend_verification'),


	# Password reset
	url(r'^password_reset/$', 
		views.PasswordResetBeginView.as_view(), name='password_reset_begin'),
	url(r'^password_reset/email/$', 
		views.PasswordResetEmailView.as_view(), name='password_reset_email'),
	url(r'^password_reset/sent/$', 
		views.PasswordResetSentView.as_view(), name='password_reset_sent'),
	url(r'^password_reset/(?P<token>[^<>\'"@]+)/$', 
		views.PasswordResetView.as_view(), name='password_reset'),


	# Not my account
	url(r'^not_my_account/confirmed/$',
		views.NotMyAccountConfirmedView.as_view(), name='not_my_account_confirmed'),
	url(r'^not_my_account/$',
		views.NotMyAccountNoUserView.as_view(), name='not_my_account_no_user'),
	url(r'^not_my_account/(?P<token>[^<>\'"@]+)/$',
		views.NotMyAccountView.as_view(), name='not_my_account'),


	# Token expired
	url(r'^token_expired/$', views.TokenExpiredView.as_view(), name='token_expired'),
	

	# Account Deactivation.
	url(r'^deactivate/$', views.DeactivateAccountView.as_view(), name='deactivate'),
	url(r'^deactivated/$', views.DeactivatedAccountView.as_view(), name='deactivated')

]

# ----------------------------------------------------------------------------------------

ulo/config/urls.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports

# Core django imports
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

# Thrid party app imports

# Project imports
from pages.views import HomeAuthView, NavigationView
from users.views import SignUpView, LoginView, LogoutView

# ----------------------------------------------------------------------------------------


# TO SERVE MEDIA FILES IN DEVELOPMENT ONLY
from django.conf.urls.static import static

# ----------------------------------------------------------------------------------------

urlpatterns = [

	# PAGES APP

	url(r'^$', HomeAuthView.as_view(), name='home'),

	# Site navigation when js is disabled.
	url(r'^navigation/$', NavigationView.as_view(), name='navigation'),


	# SEARCH APP

	url(r'^search/', include('search.urls', namespace='search')),


	# POSTS APP

	url(r'^post/', include('posts.urls', namespace='posts')),


	# USERS APP

	url(r'^user/', include('users.urls', namespace='users')),

	url(r'^signup/$', SignUpView.as_view(), name='signup'),

	url(r'^login/(\?redirect_to=(?P<redirect_to>[^<>\'"@]*/))?$', LoginView.as_view(), name='login'),
	
	url(r'^logout/$', LogoutView.as_view(), name='logout'),


	# COMMENTS APP

	url(r'^comment/', include('comments.urls', namespace='comments')),


	# ACCOUNTS APP
	
	url(r'^accounts/', include('accounts.urls', namespace='accounts')),


	# SETTINGS APP

	url(r'^settings/', include('settings.urls', namespace='settings')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ----------------------------------------------------------------------------------------

ulo/posts/urls.py
"""
Posts URL Configuration
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	# Post form
	url(r'^$', views.PostView.as_view(), name='post'),

	# Post detail page
	url(r'^(?P<pk>[\d]+)/$', views.PostDetailView.as_view(), name='detail'),

	# Post vote
	url(r'^(?P<pk>[\d]+)/vote/$', views.PostVoteView.as_view(), name='vote'),

	# Image post handler
	url(r'^image/$', views.PostImageView.as_view(), name='image'),
	
	# Video post handler
	url(r'^video/$', views.PostVideoView.as_view(), name='video'),

	# Comment
	url(r'^(?P<pk>[\d]+)/comment/$', views.PostCommentView.as_view(), name='comment'),
	url(r'^(?P<pk>[\d]+)/comment/load/$', views.PostCommentLoadView.as_view(), name='comment_load'),

	# Update post
	url(r'^(?P<pk>[\d]+)/update/$', views.PostUpdateView.as_view(), name='update'),
	
	# Delete post
	url(r'^(?P<pk>[\d]+)/delete/$', views.PostDeleteView.as_view(), name='delete'),

	# Report post
	url(r'^(?P<pk>[\d]+)/report/$', views.PostReportView.as_view(), name='report'),
	url(r'^report/complete/$', views.PostReportCompleteView.as_view(), name='report_complete'),

	# Post actions menu (JS disabled)
	url(r'^(?P<pk>[\d]+)/actions/$', views.PostActionsView.as_view(), name='actions'),

]

# ----------------------------------------------------------------------------------------

ulo/search/urls.py
"""
Accounts URL Configuration
The `urlpatterns` list routes URLs to views.
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [


	url(r'^$', views.SearchView.as_view(), name='search'),

	url(r'^autocomplete/$', views.AutocompleteView.as_view(), name='autocomplete')

]

# ----------------------------------------------------------------------------------------

ulo/settings/urls.py
"""
Settings URL Configuration
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	url(r'^account/$', views.AccountSettingsView.as_view(), name='account'),

	url(r'^password/$', views.PasswordSettingsView.as_view(), name='password'),

	# url(r'^notifications/$',
	# 	views.NotificationSettingsView.as_view(), name='notifications'),
]

# ----------------------------------------------------------------------------------------

ulo/templates/base.html
{# base html template #}
{% load staticfiles i18n %}

<!DOCTYPE html>

<html lang="en">

  <head>

    <!-- Meta ======================================================================== -->

    <meta charset="utf-8">

    <meta http-equiv="x-ua-compatible" content="IE=edge">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Used by search engines -->
    <meta name="description" content="Video sharing">

    <!-- Search keywords -->
    <meta name="keywords" content="video, music, vlogs, social, sharing, free, upload">
    
    <!-- Indicates if the search engine should add this page to their results -->
    <meta name="robots" content="follow">
    
    <meta name="author" content="TA">

    <!-- Page specific Meta. Each tag must be given the class "meta_tag" -->
    {% block meta %}{% endblock meta %}

    <!-- END Meta ==================================================================== -->


    <!-- Page Title ================================================================== -->
    
    <title>{% block title %}{{ site_name }}{% endblock title %}</title>

    <!-- END Page Title ============================================================== -->

    
    <!-- CSS ========================================================================= -->

    <!-- Site wide CSS -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css">

    <!-- Page specific CSS. Each link must be given the class "css_file" -->
    {% block css %}{% endblock css %}
    
    <!-- END CSS ===================================================================== -->

  </head>


  <body class="preload">

    <!-- Allow screen readers to jump over the navigation menu ======================= -->
    
    <a id="skip_nav" href="#main_content" title="Skip navigation">Skip navigation</a>
    
    <!-- End Allow screen readers to jump over the navigation menu =================== -->


    <!-- navigation ================================================================== -->

    <header role="banner">
        
        <nav class="nav_bar container" role="navigation">
            
            <div id="nav_search" class="col box_border">

                <div class="search_wrapper">

                    <div class="cell">
                        
                        <div class="search_form">

                            <div class="search_close">

                                <button class="close icon icon_cross" type="button">
                                
                                    <span class="hide">Close</span>

                                </button>

                            </div>

                            <form id="nav_search_form" action="{% url 'search:search' %}" method="get">

                                <input class="box_border" type="search" name="q" autofocus="autofocus" value="{{ q }}" autocomplete="off" placeholder="Search {{ site_name }}">

                                <input class="query_filter" type="hidden" name="{{ query_filter.FILTER_KEY }}" value="{{ query_filter_value }}">

                                <button class="toggle_filter_ul" data-toggle="filter_ul" type="button">

                                    <span class="icon icon_down_arrow"></span>
                                    <span class="hide">Filters</span>

                                </button>

                            </form>


                            <div class="search_data">

                                <ul id="filter_ul">

                                    <li class="filter" data-icon="video" data-value="{{ query_filter.VIDEO }}">
                                        Videos
                                    </li>
                                    
                                    <li class="filter" data-icon="account" data-value="{{ query_filter.ACCOUNT }}">
                                        Accounts
                                    </li>
                                
                                </ul>

                                <div id="suggestions">

                                    <ul class="posts_suggestions"></ul>

                                    <ul class="users_suggestions"></ul>

                                </div>

                            </div>

                        </div>

                    </div>

                    <div class="cell search_submit">

                        <button class="submit icon icon_search" type="button">
                            
                            <span class="hide">Search</span>

                        </button>

                    </div>

                </div>

            </div>

            <div class="col nav_logo">

                <a href="{% url 'home' %}" class="icon icon_logo" data-apl="true" title="Home">
                    <span class="hide">Home</span>
                </a>

            </div>

            <div class="col nav_menu">

                <a href="{% url 'navigation' %}" id="toggle_nav_ul" data-toggle="nav_ul" title="Menu">
                    <span class="icon icon_menu"></span>
                    <span class="hide">Menu</span>
                </a>

                <ul id="nav_ul" class="box_border container">

                    {% if user.is_authenticated %}

                    <li>
                        
                        <a href="{% url 'users:profile' user.username %}" class="ellipsis" data-apl="true" title="{{ user.name }}">{{ user.get_short_name }}</a>

                    </li><li>
                        
                        <a href="{% url 'posts:post' %}" class="ellipsis" data-apl="true" title="Post">Post</a>

                    </li><li>
                        
                        <a href="{% url 'settings:account' %}" class="ellipsis" data-apl="true" title="Settings">Settings</a>

                    </li><li>
                        
                        <a href="{% url 'logout' %}" class="ellipsis" title="Log out">Log&nbsp;out</a>

                    </li>

                    {% else %}

                    <li>
                        
                        <a href="{% url 'signup' %}" class="ellipsis" data-apl="true" title="Sign up">Sign&nbsp;up</a>

                    </li><li>
                        
                        <a href="{% url 'login' %}" class="ellipsis" data-apl="true" title="Log in">Log&nbsp;in</a>

                    </li>

                    {% endif %}
                
                </ul>

            </div>

        </nav>

        <span class="loading_bar"></span>

    </header>

    <!-- END navigation ============================================================== -->


    


    <!-- Main Content ================================================================ -->
    
    <div id="content_container">

        <!-- messages ==================================================================== -->

        <div id="messages" class="box_border{% if messages %} show no_js"{% endif %}">

            <div class="wrapper">

                <div class="container box_border">
                     
                    <div class="text"> 
                    
                        {% for message in messages %}
                        <p {% if message.tags %}class="{{ message.tags }}"{% endif %}>
                            
                            {{ message }}
                        
                        </p>
                        {% endfor %}
                    
                    </div>

                </div>

            </div>
            
        </div>

        <!-- end messages ================================================================ -->

        <main role="main" id="main_content" class="container" data-token-id="{{ csrf_token }}"{% if user.is_authenticated %} data-auth-id="{{ user.id }}"{% endif %}>

            <!-- email confirmation ====================================================== -->

            {% if user.email_confirmed == False %}
            <div class="email_confirmation">
                
                <form id="email_confirmation_form" class="container box_border" action="{% url 'accounts:resend_verification' %}" method="get">

                    <p class="confirmation_text">
                        A confirmation message has been sent to <b class="email_address">{{user.email}}</b>. Confirm your email address to complete your account registration.
                    </p>
                    
                    <button class="resend_confirmation" type="submit">
                        Resend Email Confirmation
                    </button>
                    
                    <a data-apl="true" class="change_email" class="bold" href="{% url 'settings:account' %}">
                        Change&nbsp;email&nbsp;address
                    </a>
            
                </form>
            
            </div>
            {% endif %}

            <!-- END email confirmation ================================================== -->

            {% block content %}{% endblock content %}
            
        </main>

    </div>

    <!-- END Main Content ============================================================ -->
    

    <!-- Javascript ================================================================== -->
    
    {% block base_js %}
    
    <!-- Site wide Javascript files -->
    <script src="{% static 'js/libraries/jquery-1.12.2.min.js' %}"></script>
    <script src="{% static 'js/polyfills/fastclick.min.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    
    {% endblock base_js %}

    <!-- Page specific Javascript files. Each file must be given the class "js_file" -->
    {% block js %}{% endblock js %}

    <!-- END Javascript ============================================================== -->


  </body>
</html>

ulo/templates/base_ajax.html
{# base html template for ajax page loads #}

<ul id="nav_ul" class="box_border">

    {% if user.is_authenticated %}

    <li>
        
        <a href="{% url 'users:profile' user.username %}" class="ellipsis" data-apl="true" title="{{ user.get_short_name }}">{{ user.get_short_name }}</a>

    </li><li>
        
        <a href="{% url 'posts:post' %}" class="ellipsis" data-apl="true" title="Post">Post</a>

    </li><li>
        
        <a href="{% url 'settings:account' %}" class="ellipsis" data-apl="true" title="Settings">Settings</a>

    </li><li>
        
        <a href="{% url 'logout' %}" class="ellipsis" title="Log out">Log&nbsp;out</a>

    </li>

    {% else %}

    <li>
        
        <a href="{% url 'signup' %}" class="ellipsis" data-apl="true" title="Sign up">Sign&nbsp;up</a>

    </li><li>
        
        <a href="{% url 'login' %}" class="ellipsis" data-apl="true" title="Log in">Log&nbsp;in</a>

    </li>

    {% endif %}

</ul>


<!-- Page specific Meta. Each tag must be given the class "meta_tag" -->
<span id="page_meta">{% block meta %}{% endblock meta %}</span>

<!-- Page specific CSS. Each link must be given the class "css_file" -->
<span id="page_css">{% block css %}{% endblock css %}</span>

<!-- Page Title -->
<span id="page_title">{% block title %}Ulo{% endblock title %}</span>

<!-- Main Content -->
<main role="main" id="main_content" class="container">

    <!-- email confirmation ====================================================== -->

    {% if user.email_confirmed == False %}
    <div class="email_confirmation">
                
        <form id="email_confirmation_form" class="container box_border" action="{% url 'accounts:resend_verification' %}" method="get">

            <p class="confirmation_text">
                A confirmation message has been sent to <b class="email_address">{{user.email}}</b>. Confirm your email address to complete your account registration.
            </p>
            
            <button class="resend_confirmation" type="submit">
                Resend Email Confirmation
            </button>
            
            <a data-apl="true" class="change_email" class="bold" href="{% url 'settings:account' %}">
                Change&nbsp;email&nbsp;address
            </a>
    
        </form>
    
    </div>
    {% endif %}

    <!-- END email confirmation ================================================== -->

	{% block content %}{% endblock content %}

</main>

<!-- Page specific Javascript files. Each script must be given the class "js_file" -->
<span id="page_js">{% block js %}{% endblock js %}</span>